# Generated by Django 5.2.6 on 2025-10-06 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
