# Generated by Django 5.2.6 on 2025-10-11 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0006_alter_photo_album'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='is_favourite',
            field=models.BooleanField(default=False),
        ),
    ]
