# Generated by Django 5.2.6 on 2025-10-28 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0008_video'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='Video_file',
            new_name='video_file',
        ),
    ]
